Some common terms to remember:
1. Corpus
2. Vocabulary
3. Document
4. Word

# **Bag of Words**

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame({"text":["people watch molvi",
                         "molvi watch molvi",
                         "people write comment",
                          "molvi write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [4]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [5]:
bow = cv.fit_transform(df['text'])

In [8]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [9]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [6]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [7]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [8]:
X = bow.toarray()
y = df['output']

#  **N-Grams**

In [9]:
df = pd.DataFrame({"text":["people watch molvi",
                         "molvi watch molvi",
                         "people write comment",
                          "molvi write comment"],"output":[1,1,0,0]})

df

text  output
0    people watch molvi       1
1     molvi watch molvi       1
2  people write comment       0
3   molvi write comment       0

In [10]:
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [11]:
bow = cv.fit_transform(df['text'])

In [12]:
print(cv.vocabulary_)

{'people watch': 2, 'watch molvi': 4, 'molvi watch': 0, 'people write': 3, 'write comment': 5, 'molvi write': 1}


In [13]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [ ]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [14]:
bow = cv.fit_transform(df['text'])

In [15]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [ ]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


# **TF-IDF (Term frequency- Inverse document frequency)**

In [16]:
df = pd.DataFrame({"text":["people watch molvi",
                         "molvi watch molvi",
                         "people write comment",
                          "molvi write comment"],"output":[1,1,0,0]})

df

text  output
0    people watch molvi       1
1     molvi watch molvi       1
2  people write comment       0
3   molvi write comment       0

In [17]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid= TfidfVectorizer()

In [18]:
arr = tfid.fit_transform(df['text']).toarray()

In [19]:
arr

array([[0.        , 0.49681612, 0.61366674, 0.61366674, 0.        ],
       [0.        , 0.8508161 , 0.        , 0.52546357, 0.        ],
       [0.57735027, 0.        , 0.57735027, 0.        , 0.57735027],
       [0.61366674, 0.49681612, 0.        , 0.        , 0.61366674]])

In [20]:
 print(tfid.idf_)

[1.51082562 1.22314355 1.51082562 1.51082562 1.51082562]
